# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Spyder\TemperatureSensorApplication\Eric\TemperatureSensor50x50\main.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(917, 509)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 681, 36))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.COM_Input = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.COM_Input.setObjectName("COM_Input")
        self.horizontalLayout.addWidget(self.COM_Input)
        self.COM_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.COM_Button.setObjectName("COM_Button")
        self.horizontalLayout.addWidget(self.COM_Button)
        self.COM1_Input = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.COM1_Input.setObjectName("COM1_Input")
        self.horizontalLayout.addWidget(self.COM1_Input)
        self.COM1_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.COM1_Button.setObjectName("COM1_Button")
        self.horizontalLayout.addWidget(self.COM1_Button)
        self.COM2_Input = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.COM2_Input.setObjectName("COM2_Input")
        self.horizontalLayout.addWidget(self.COM2_Input)
        self.COM2_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.COM2_Button.setObjectName("COM2_Button")
        self.horizontalLayout.addWidget(self.COM2_Button)
        self.Exit = QtWidgets.QPushButton(self.centralWidget)
        self.Exit.setGeometry(QtCore.QRect(690, 420, 112, 34))
        self.Exit.setObjectName("Exit")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(530, 100, 366, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.StartCal_Input = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.StartCal_Input.setObjectName("StartCal_Input")
        self.horizontalLayout_2.addWidget(self.StartCal_Input)
        self.DegGapCal_Input = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.DegGapCal_Input.setObjectName("DegGapCal_Input")
        self.horizontalLayout_2.addWidget(self.DegGapCal_Input)
        self.TimesCal_Input = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.TimesCal_Input.setObjectName("TimesCal_Input")
        self.horizontalLayout_2.addWidget(self.TimesCal_Input)
        self.Cal = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.Cal.setObjectName("Cal")
        self.horizontalLayout_2.addWidget(self.Cal)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(530, 170, 366, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.StartVer_Input = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.StartVer_Input.setObjectName("StartVer_Input")
        self.horizontalLayout_4.addWidget(self.StartVer_Input)
        self.DegGapVer_Input = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.DegGapVer_Input.setObjectName("DegGapVer_Input")
        self.horizontalLayout_4.addWidget(self.DegGapVer_Input)
        self.TimesVer_Input = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.TimesVer_Input.setObjectName("TimesVer_Input")
        self.horizontalLayout_4.addWidget(self.TimesVer_Input)
        self.Ver = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.Ver.setObjectName("Ver")
        self.horizontalLayout_4.addWidget(self.Ver)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(530, 360, 301, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.TimesDynamic_Input = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.TimesDynamic_Input.setObjectName("TimesDynamic_Input")
        self.horizontalLayout_5.addWidget(self.TimesDynamic_Input)
        self.Dynamic = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.Dynamic.setObjectName("Dynamic")
        self.horizontalLayout_5.addWidget(self.Dynamic)
        self.DynamicTimes_Label = QtWidgets.QLabel(self.centralWidget)
        self.DynamicTimes_Label.setGeometry(QtCore.QRect(530, 340, 101, 16))
        self.DynamicTimes_Label.setObjectName("DynamicTimes_Label")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 80, 451, 381))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Three = QtWidgets.QOpenGLWidget(self.gridLayoutWidget)
        self.Three.setObjectName("Three")
        self.gridLayout.addWidget(self.Three, 3, 0, 1, 1)
        self.One = QtWidgets.QOpenGLWidget(self.gridLayoutWidget)
        self.One.setObjectName("One")
        self.gridLayout.addWidget(self.One, 0, 0, 1, 1)
        self.Four = QtWidgets.QOpenGLWidget(self.gridLayoutWidget)
        self.Four.setObjectName("Four")
        self.gridLayout.addWidget(self.Four, 3, 1, 1, 1)
        self.Two = QtWidgets.QOpenGLWidget(self.gridLayoutWidget)
        self.Two.setObjectName("Two")
        self.gridLayout.addWidget(self.Two, 0, 1, 1, 1)
        self.Animation = QtWidgets.QPushButton(self.centralWidget)
        self.Animation.setGeometry(QtCore.QRect(540, 420, 112, 34))
        self.Animation.setObjectName("Animation")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(530, 70, 231, 31))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.CalStart_label = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.CalStart_label.setObjectName("CalStart_label")
        self.horizontalLayout_7.addWidget(self.CalStart_label)
        self.CalDegGap_label = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.CalDegGap_label.setObjectName("CalDegGap_label")
        self.horizontalLayout_7.addWidget(self.CalDegGap_label)
        self.CalTimes_label = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.CalTimes_label.setObjectName("CalTimes_label")
        self.horizontalLayout_7.addWidget(self.CalTimes_label)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(530, 140, 231, 31))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.VerStart_label = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.VerStart_label.setObjectName("VerStart_label")
        self.horizontalLayout_8.addWidget(self.VerStart_label)
        self.VerDegGap_label = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.VerDegGap_label.setObjectName("VerDegGap_label")
        self.horizontalLayout_8.addWidget(self.VerDegGap_label)
        self.VerTimes_label = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.VerTimes_label.setObjectName("VerTimes_label")
        self.horizontalLayout_8.addWidget(self.VerTimes_label)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.COM_Button.setText(_translate("MainWindow", "Open"))
        self.COM1_Button.setText(_translate("MainWindow", "Open"))
        self.COM2_Button.setText(_translate("MainWindow", "Open"))
        self.Exit.setText(_translate("MainWindow", "Exit"))
        self.Cal.setText(_translate("MainWindow", "Cal"))
        self.Ver.setText(_translate("MainWindow", "Verification"))
        self.Dynamic.setText(_translate("MainWindow", "Dynamic"))
        self.DynamicTimes_Label.setText(_translate("MainWindow", "Times(>=2)"))
        self.Animation.setText(_translate("MainWindow", "Animation"))
        self.CalStart_label.setText(_translate("MainWindow", "Start Deg."))
        self.CalDegGap_label.setText(_translate("MainWindow", "Deg. Gap"))
        self.CalTimes_label.setText(_translate("MainWindow", "Times"))
        self.VerStart_label.setText(_translate("MainWindow", "Start Deg."))
        self.VerDegGap_label.setText(_translate("MainWindow", "Deg. Gap"))
        self.VerTimes_label.setText(_translate("MainWindow", "Times"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

